import { Header } from "@/components/header";
import { SheetProvider } from "@/provider/sheet-provider";
import type { Metadata } from "next";
import { Suspense } from "react";

import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (<>
<SheetProvider/>
<Header/>
        <Toaster/>

<Suspense fallback={<div className="p-6">Loading transactions page...</div>}>
      {children}
    </Suspense>
    
  </>
  
  );
}
